"""
SmartSalary India — Occupation & Taxpayer Enums
Defines 7-tier occupation hierarchy levels, taxpayer economic types, and business structures.
"""

from enum import StrEnum


class TaxpayerType(StrEnum):
    SALARIED_INDIVIDUAL = "SALARIED_INDIVIDUAL"
    SELF_EMPLOYED_PROFESSIONAL = "SELF_EMPLOYED_PROFESSIONAL"
    BUSINESS_OWNER = "BUSINESS_OWNER"
    FREELANCER = "FREELANCER"
    GIG_WORKER = "GIG_WORKER"
    FARMER_AGRICULTURIST = "FARMER_AGRICULTURIST"
    PENSIONER = "PENSIONER"
    STUDENT_WITH_INCOME = "STUDENT_WITH_INCOME"
    HOMEMAKER_WITH_INCOME = "HOMEMAKER_WITH_INCOME"
    MIXED_INCOME_INDIVIDUAL = "MIXED_INCOME_INDIVIDUAL"


class ResidentialStatus(StrEnum):
    RESIDENT = "RESIDENT"
    NON_RESIDENT = "NON_RESIDENT"
    RNOR = "RNOR"  # Resident but Not Ordinarily Resident


class BusinessStructure(StrEnum):
    SOLE_PROPRIETORSHIP = "SOLE_PROPRIETORSHIP"
    PARTNERSHIP = "PARTNERSHIP"
    LLP = "LLP"
    PRIVATE_LIMITED = "PRIVATE_LIMITED"
    PUBLIC_LIMITED = "PUBLIC_LIMITED"
    HUF = "HUF"
    COOPERATIVE = "COOPERATIVE"
    OTHER = "OTHER"


class EmploymentType(StrEnum):
    FULL_TIME_SALARIED = "FULL_TIME_SALARIED"
    PART_TIME_SALARIED = "PART_TIME_SALARIED"
    CONTRACT = "CONTRACT"
    CONSULTANT = "CONSULTANT"
    FREELANCE = "FREELANCE"
    DIRECTOR_SALARIED = "DIRECTOR_SALARIED"
