from enum import StrEnum


class TaxRegime(StrEnum):
    OLD = "OLD"
    NEW = "NEW"


class RuleStatus(StrEnum):
    DRAFT = "DRAFT"
    VERIFIED = "VERIFIED"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    RETIRED = "RETIRED"


class CalculationStatus(StrEnum):
    DRAFT = "DRAFT"
    CALCULATED = "CALCULATED"
    VERIFIED = "VERIFIED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class LineItemCategory(StrEnum):
    INCOME = "INCOME"
    EXEMPTION = "EXEMPTION"
    DEDUCTION = "DEDUCTION"
    TAXABLE_INCOME = "TAXABLE_INCOME"
    TAX_SLAB = "TAX_SLAB"
    REBATE = "REBATE"
    MARGINAL_RELIEF = "MARGINAL_RELIEF"
    SURCHARGE = "SURCHARGE"
    CESS = "CESS"
    TAX_LIABILITY = "TAX_LIABILITY"
    PF_CONTRIBUTION = "PF_CONTRIBUTION"
    PROFESSIONAL_TAX = "PROFESSIONAL_TAX"
    EMPLOYEE_DEDUCTION = "EMPLOYEE_DEDUCTION"
    EMPLOYER_CONTRIBUTION = "EMPLOYER_CONTRIBUTION"
    TAKE_HOME = "TAKE_HOME"


class LineItemType(StrEnum):
    BASIC = "BASIC"
    DA = "DA"
    HRA = "HRA"
    SPECIAL_ALLOWANCE = "SPECIAL_ALLOWANCE"
    BONUS = "BONUS"
    OTHER_ALLOWANCES = "OTHER_ALLOWANCES"
    GROSS_SALARY = "GROSS_SALARY"
    STANDARD_DEDUCTION = "STANDARD_DEDUCTION"
    SECTION_80C = "SECTION_80C"
    SECTION_80D = "SECTION_80D"
    SECTION_87A_REBATE = "SECTION_87A_REBATE"
    REBATE_MARGINAL_RELIEF = "REBATE_MARGINAL_RELIEF"
    SURCHARGE_AMOUNT = "SURCHARGE_AMOUNT"
    SURCHARGE_MARGINAL_RELIEF = "SURCHARGE_MARGINAL_RELIEF"
    HEALTH_EDUCATION_CESS = "HEALTH_EDUCATION_CESS"
    TOTAL_ANNUAL_TAX = "TOTAL_ANNUAL_TAX"
    EMPLOYEE_EPF = "EMPLOYEE_EPF"
    EMPLOYER_EPF = "EMPLOYER_EPF"
    EMPLOYER_EPS = "EMPLOYER_EPS"
    EMPLOYER_EDLI = "EMPLOYER_EDLI"
    MONTHLY_PT = "MONTHLY_PT"
    ANNUAL_PT = "ANNUAL_PT"
    OTHER_DEDUCTION = "OTHER_DEDUCTION"
    ESTIMATED_TAKE_HOME = "ESTIMATED_TAKE_HOME"


class Gender(StrEnum):
    ALL = "ALL"
    MALE = "MALE"
    FEMALE = "FEMALE"


class ResidentialStatus(StrEnum):
    RESIDENT = "RESIDENT"
    NON_RESIDENT = "NON_RESIDENT"
    NOT_ORDINARILY_RESIDENT = "NOT_ORDINARILY_RESIDENT"
