from enum import StrEnum


class DiscrepancyCode(StrEnum):
    """
    Standardized, machine-readable discrepancy reason codes for three-way reconciliation.
    """

    # Earnings Mismatches
    GROSS_MISMATCH = "GROSS_MISMATCH"
    BASIC_MISMATCH = "BASIC_MISMATCH"
    HRA_MISMATCH = "HRA_MISMATCH"
    SPECIAL_ALLOWANCE_MISMATCH = "SPECIAL_ALLOWANCE_MISMATCH"
    UNEXPECTED_COMPONENT = "UNEXPECTED_COMPONENT"
    UNSUPPORTED_COMPONENT = "UNSUPPORTED_COMPONENT"

    # Statutory Deductions Mismatches
    EPF_MISMATCH = "EPF_MISMATCH"
    PF_UNDER_DEDUCTION = "PF_UNDER_DEDUCTION"
    PF_OVER_DEDUCTION = "PF_OVER_DEDUCTION"
    MISSING_PF = "MISSING_PF"

    PT_MISMATCH = "PT_MISMATCH"
    MISSING_PT = "MISSING_PT"

    TDS_MISMATCH = "TDS_MISMATCH"
    MISSING_TDS = "MISSING_TDS"

    ESI_MISMATCH = "ESI_MISMATCH"

    # Totals and Accounting Formulas
    NET_PAY_MISMATCH = "NET_PAY_MISMATCH"
    TOTAL_DEDUCTIONS_MISMATCH = "TOTAL_DEDUCTIONS_MISMATCH"
    DOCUMENT_FORMULA_MISMATCH = "DOCUMENT_FORMULA_MISMATCH"
    EMPLOYER_CONTRIBUTION_MISMATCH = "EMPLOYER_CONTRIBUTION_MISMATCH"

    # Tolerances & References
    ROUNDING_VARIANCE = "ROUNDING_VARIANCE"
    PAYROLL_REFERENCE_MISSING = "PAYROLL_REFERENCE_MISSING"
    STATUTORY_REFERENCE_MISSING = "STATUTORY_REFERENCE_MISSING"
